on:
  push:
    branches:
      - main
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: ts-shader-loader
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
